[theme]
primaryColor = "#00FF00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[server]
enableCORS = false

[general]
email = "your-email@example.com"

[branding]
logo = "logo.png"
