[theme]
primaryColor = "#6c63ff"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[ui]
hideTopBar = false

[client]
showErrorDetails = true

[general]
# Your logo must match this filename
#logo = "logo.png"
