[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
logo = "logo.png"
